name: tapl

dependencies:
  - base >= 4.7 && < 5
  - QuickCheck
  - megaparsec
  - text

library:
  source-dirs: src

executables:
  tapl-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tapl
      - haskeline

tests:
  tapl-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tapl
      - hspec
